services:
  db:
    image: postgres:18
    container_name: taxi_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: taxi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always

volumes:
  postgres_data: